language: node_js
sudo: false
node_js:
  - 10
  - 12
  - 13
cache: npm
services:
  - docker
install:
  - npm install
script:
  - npm test
  - npm run lint
jobs:
  include:
    - stage: check-docker
      node_js: 13
      install:
        - docker-compose build
      script:
        - docker-compose run remote-pub npm test