version: "3.7"
services:
  remote-pub:
    build:
      context: ./
      target: dev
    volumes:
    - ./:/app
    - /app/node_modules/
    ports:
      - 5000:5000
  remote-pub-prod:
    build:
      context: ./
      target: prod
    ports:
      - 5000:5000